commands:
  ban-command: "minecraft:ban %player% %reason%"
  unban-command: "minecraft:pardon %player%"

settings:
  language: "ru"  # Доступные языки: en, ru, uk, pl, zh, fr, es
  starting-hearts: 10
  min-hearts: 1
  max-hearts: 10
  modify-hearts: true  # Если true - количество сердец зависит от жизней, если false - всегда стандартное количество сердец

items:
  life-stealer:
    name: "&#FB0808Ш&#F10909п&#E70A0Aр&#DD0C0Cи&#D30D0Dц &#C00F0Fж&#B61010и&#AC1212з&#A21313н&#981414и"
    lore:
      - "&7Позволяет украсть одну жизнь"
      - "&7у другого игрока"
    material: "STICK"
    glow: true

  # %lifelimiter_hearts% - текущее количество жизней игрока
  # %lifelimiter_max_hearts% - максимальное количество жизней
  # %lifelimiter_min_hearts% - минимальное количество жизней