commands:
  ban-command: "minecraft:ban %player% %reason%"
  unban-command: "minecraft:pardon %player%"

settings:
  language: "ru"  # Доступные языки: en, ru, uk, pl, zh, fr, es
  starting-hearts: 10
  min-hearts: 1
  max-hearts: 10

  # %lifelimiter_hearts% - текущее количество жизней игрока
  # %lifelimiter_max_hearts% - максимальное количество жизней
  # %lifelimiter_min_hearts% - минимальное количество жизней